export const FETCH_POSTS = 'FETCH_POSTS';
export const RECEIVE_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const RECEIVE_POSTS_FAIL = 'RECEIVE_POSTS_FAIL';

export const SEND_POSTS = 'SEND_POSTS';
export const SEND_POSTS_SUCCESS = 'SEND_POSTS_SUCCESS';
export const SEND_POSTS_FAIL = 'SEND_POSTS_FAIL';