export const FETCH_POSTS = 'FETCH_POSTS';
export const RECEIVE_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const RECEIVE_POSTS_FAIL = 'RECEIVE_POSTS_FAIL';

export const SEND_POST = 'SEND_POSTS';
export const SEND_POST_SUCCESS = 'SEND_POST_SUCCESS';
export const SEND_POST_FAIL = 'SEND_POST_FAIL';

export const FETCH_CURRENT_POST = 'FETCH_CURRENT_POST';
export const RECEIVE_CURRENT_POST_SUCCESS = 'RECEIVE_CURRENT_POST_SUCCESS';
export const RECEIVE_CURRENT_POST_FAIL = 'RECEIVE_CURRENT_POST_FAIL';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';